name : hello-world       
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest                                                                                  
    steps:
      - name : print hello
        run : echo "Hello World"
  second_job:
      runs-on : ubuntu-latest
      steps:
         - name : print hello again
           run : echo "Hello World again"  

         - name : I will pass 
           run: exit code 0

         - name : Goodbye
           run: echo "goodbye"
